version: '3'
services:
  neurender-ctl:
    image: airstudio/neurender-ctl:latest
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VAST_AI_KEY=${VAST_AI_KEY}
    stdin_open: true
    tty: true
    volumes:
      - ${HOST_VOLUME}:/data